PREFIX=$HOME/.config/git/openssl-
export GIT_FILTER_OPENSSL_PASSWORD=${GIT_FILTER_OPENSSL_PASSWORD:-$(cat ${PREFIX}password)}
export GIT_FILTER_OPENSSL_SALT=${GIT_FILTER_OPENSSL_SALT:-$(cat ${PREFIX}salt)}

